export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST";
export const GET_CUSTOMER_INFOR = "GET_CUSTOMER_INFOR";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
